sudo: false

git:
  depth: 1

branches:
  only:
    - master
    - /^greenkeeper.*$/

language: node_js

# cache node modules
cache:
  directories:
    - $HOME/.npm
    - node_modules

node_js:
  - "lts/*"

before_install:
  - npm install -g npm@latest
